In [4]:
import pandas as pd
import matplotlib.pyplot as plt
# from IPython.display import Image, Video

# 介绍
Numpy 提供多维数组对象以及一系列操作数组的函数, 可以说其几乎是每一个Python科学计算软件的基础库.

In [5]:
import numpy as np

Numpy的核心数据结构是ndarray, 它用来存储具有相同数据类型的多维数组. 除了数据, ndarry也包含数组的shape, size, ndim, nbytes, dtype.

In [7]:
np.ndarray?

In [8]:
d0 = np.array([[1,2],[3,4]])

In [9]:
d0

array([[1, 2],
       [3, 4]])

In [10]:
type(d0), d0.shape, d0.size, d0.ndim, d0.dtype, d0.nbytes

(numpy.ndarray, (2, 2), 4, 2, dtype('int32'), 16)

为什么需要numpy? 速度! 简单! 粗略比较一下速度.

In [11]:
a0 = np.arange(10000)
t0 = %timeit -o [i**2 for i in a0]

1000 loops, best of 3: 1.93 ms per loop


In [12]:
a1 = np.arange(10000)
t1 = %timeit -o a1**2

The slowest run took 5.50 times longer than the fastest. This could mean that an intermediate result is being cached.
100000 loops, best of 3: 8.22 µs per loop


In [13]:
t0.best/t1.best

234.49457122985947

# 数据类型
Numpy Dtypes

详细参考: numpy datatypes.

In [14]:
x = np.array([1, 2]) # Let numpy choose the datatype
y = np.array([1.0, 2.0])  # Let numpy choose the datatype
z = np.array([1, 2], dtype=np.int64)

print(x.dtype, y.dtype, z.dtype)

int32 float64 int64


In [15]:
z.nbytes*8 # nbits

128

In [16]:
x1 = x + 0.3
print(x1, x1.dtype)

[1.3 2.3] float64


In [17]:
z[0] = 3.5
z

array([3, 2], dtype=int64)

如何使用类型: 一般指定int, float, complex 即可, 不需要细分int16, int32等

In [18]:
np.sqrt([-1, 2, 3])

E:\setup\Anaconda3-4.2.0-py35\lib\site-packages\ipykernel\__main__.py:1: RuntimeWarning: invalid value encountered in sqrt
  if __name__ == '__main__':


array([       nan, 1.41421356, 1.73205081])

In [19]:
np.sqrt([-1, 2, 3], dtype=np.complex)

array([0.        +1.j, 1.41421356+0.j, 1.73205081+0.j])

# 存储顺序
多维数组在内存中是连续储存的, 本质上可以看成是一维, 如何将内存中数据映射到多维数组中取决于数组是按行存储的还是按列存储的. 例如有四个整数1,2,3,4, 那么:

按行存储就是: [[1, 2], [3, 4]]
按列存储就是: [[1, 3], [2, 4]]
Fotran是按列存储的, C是按行存储的.

In [20]:
a = np.arange(6, dtype=np.int8)

In [21]:
a

array([0, 1, 2, 3, 4, 5], dtype=int8)

In [22]:
a1 = a.reshape(2,3, order="F")
a1

array([[0, 2, 4],
       [1, 3, 5]], dtype=int8)

In [23]:
a2 = a.reshape(2, 3)
a2

array([[0, 1, 2],
       [3, 4, 5]], dtype=int8)

什么时候需要考虑存储顺序?

跟其他语言交互的时候, 比如调用Fortran(Numpy, Scipy中很多数值 就是调用Fortran的, Anconda现在默认使用intel mkl也是Fortran的), 但是平常使用不需要关心顺序.

Numpy中使用ndarray.strides确定映射的顺序.

In [24]:
a1.strides

(1, 2)

In [25]:
a2.strides

(3, 1)

strides确定对应维度移动一个元素应内存中移动的字节数, 如对应a1, 有(1x1, 2x1), 对应a2, 有(3x1, 1x1).

某些操作, 如transpose, reshape, 只需要改变strides即可.

In [26]:
a = np.random.rand(10, 3)

In [27]:
a.strides

(24, 8)

In [28]:
b = a.transpose()

In [29]:
b.strides

(8, 24)

In [30]:
np.shares_memory(a, b)

True

In [31]:
c = a.reshape(3, 10)

In [32]:
np.shares_memory(a, c)

True

## 帮助

In [33]:
np.array?

In [34]:
np.con*?

In [35]:
>>> np.array([[1, 2], [3, 4]])

array([[1, 2],
       [3, 4]])

# 数组创建
# 从列表创建

In [36]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])

In [37]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [38]:
b

array([1, 2, 3])

In [41]:
print("a:",a.shape, a.size, type(a), np.ndim(a), a.size)
print("b:",b.shape, b.size, type(b), np.ndim(b), b.size)

a: (2, 3) 6 <class 'numpy.ndarray'> 2 6
b: (3,) 3 <class 'numpy.ndarray'> 1 3


In [43]:
len(a), len(b) # 返回第一个维度的长度

(2, 3)

In [44]:
np.array([i for i in range(10) if i % 2 == 0])

array([0, 2, 4, 6, 8])

In [45]:
a, a.shape[0], len(a)

(array([[1, 2, 3],
        [4, 5, 6]]), 2, 2)

## 使用Numpy函数创建

In [46]:
np.zeros(2, 3) # Create an array of all zeros

TypeError: data type not understood

In [47]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
np.ones((5, 5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [49]:
np.full((2, 3), 7)

array([[7, 7, 7],
       [7, 7, 7]])

In [50]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [51]:
np.random.random((2, 3))

array([[0.45876478, 0.79251043, 0.0846241 ],
       [0.54418218, 0.0191857 , 0.38711422]])

In [52]:
np.arange(9).reshape(3,-1)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
np.linspace(0, 1.0, 10)

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [56]:
np.tril(np.arange(9).reshape(3, -1)) # 返回下三角矩阵
# np.triu 返回上三角矩阵

array([[0, 0, 0],
       [3, 4, 0],
       [6, 7, 8]])

In [57]:
np.random.rand(3, 3)

array([[0.71473042, 0.95872367, 0.28969472],
       [0.32984731, 0.31908785, 0.49106201],
       [0.53514671, 0.30591923, 0.95675115]])

# 从文件读取

In [59]:
!head test.dat
!wc test.dat

'head' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
'wc' 不是内部或外部命令，也不是可运行的程序
或批处理文件。


In [61]:
# a = np.genfromtxt("test.dat", delimiter=",", comments="#")
a[:10], a.shape

In [65]:
# 保存数组到可读文件
np.savetxt("test.dat", np.random.random((1000, 5)), delimiter=",", header="show how to save array dat.\n a simple example")

# 保存二进制文件
np.savetxt("test.npy", np.random.random((1000, 5)))

In [66]:
# 读取大文件
def generate_txt_filel(length=1e6, ncols=20):
    data = np.random.random((int(length), int(ncols)))
    np.savetxt("large_text_file.csv", data, delimiter=',')
    
def iter_loadtxt(filename, delimiter=',', skiprows=0, dtype=float):
    def iter_func():
        with open(filename, 'r') as infile:
            for _ in range(skiprows):
                next(infile)
            for line in infile:
                line = line.rstrip().split(delimiter)
                for item in line:
                    yield dtype(item)
        iter_loadtxt.rowlength = len(line)
    
    data = np.fromiter(iter_func(), dtype=dtype)
    data = data.reshape((-1, iter_loadtxt.rowlength))
    return data

In [ ]:
# generate_text_file() # 477M

In [ ]:
!ls -lh large_text_file.csv

In [ ]:
%time data = np.genfromtxt('large_text_file.csv', delimiter=",")
# CPU times: user 24.2 s, sys: 8.5 s, total: 32.7 s
# Wall time: 32.8 s

In [ ]:
# %time data = iter_loadtxt('large_text_file.csv')

In [ ]:
%time data = pd.read_csv('large_text_file.csv')
CPU times: user 5.48 s, sys: 1.27 s, total: 6.75 s
Wall time: 6.13 s

# 索引与切片

In [67]:
a = np.array([[i+j for j in range(6)] for i in range(0, 60, 10)])
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [68]:
[[i+j for j in range(6)] for i in range(0, 60, 10)]

[[0, 1, 2, 3, 4, 5],
 [10, 11, 12, 13, 14, 15],
 [20, 21, 22, 23, 24, 25],
 [30, 31, 32, 33, 34, 35],
 [40, 41, 42, 43, 44, 45],
 [50, 51, 52, 53, 54, 55]]

In [69]:
np.repeat(range(5), 5)

array([0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4,
       4, 4, 4])

In [70]:
np.arange(6) + np.arange(0, 60, 10).reshape(6, -1)

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

## 索引（indexing）

In [71]:
print(a[0,0],a[1,2],a[2,2])

0 12 22


In [72]:
a[0,2] = 3

## 切片（Slicing）

In [75]:
a[:, 0], a[1, :], a[[1], :]

(array([ 0, 10, 20, 30, 40, 50]),
 array([10, 11, 12, 13, 14, 15]),
 array([[10, 11, 12, 13, 14, 15]]))

In [76]:
a[0, 3:5]

array([3, 4])

In [77]:
a[4:, 4:]

array([[44, 45],
       [54, 55]])

In [78]:
a[:, 2]

array([ 3, 12, 22, 32, 42, 52])

In [79]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

## 整数数组索引(fancing index)

In [80]:
a[[1,3],:]

array([[10, 11, 12, 13, 14, 15],
       [30, 31, 32, 33, 34, 35]])

In [81]:
a[[1,3],:] = 5
a

array([[ 0,  1,  3,  3,  4,  5],
       [ 5,  5,  5,  5,  5,  5],
       [20, 21, 22, 23, 24, 25],
       [ 5,  5,  5,  5,  5,  5],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

## 条件索引

In [82]:
a = np.random.random(10)*2 + -1 # random with(-1, 1)
a

array([ 0.70109591,  0.44687864,  0.69521746,  0.69945973, -0.12966815,
        0.74113341, -0.13099808, -0.91643527, -0.3992672 ,  0.76867557])

In [83]:
a[a>0.3] = 20

In [84]:
a>0.3, a

(array([ True,  True,  True,  True, False,  True, False, False, False,
         True]),
 array([20.        , 20.        , 20.        , 20.        , -0.12966815,
        20.        , -0.13099808, -0.91643527, -0.3992672 , 20.        ]))

In [85]:
a

array([20.        , 20.        , 20.        , 20.        , -0.12966815,
       20.        , -0.13099808, -0.91643527, -0.3992672 , 20.        ])

### copies and views

In [87]:
a = np.arange(10)
b = a[::2]
b1 = a[5:]
c = a.copy()

In [88]:
b

array([0, 2, 4, 6, 8])

In [89]:
b1

array([5, 6, 7, 8, 9])

In [90]:
c

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [91]:
np.may_share_memory(a, b)

True

In [92]:
np.may_share_memory(a, c)

False

In [93]:
np.may_share_memory(b, b1)

True

In [94]:
a.base is c

False

In [95]:
b.base

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [98]:
print(c.base)

None


In [99]:
a = np.random.rand(5, 3)

In [100]:
a

array([[0.66236332, 0.48459376, 0.3828329 ],
       [0.44641996, 0.4446403 , 0.08676116],
       [0.24292748, 0.63716174, 0.14630338],
       [0.49348687, 0.90616509, 0.81849973],
       [0.84486983, 0.04786377, 0.5457139 ]])

In [101]:
c = a.flatten()
c

array([0.66236332, 0.48459376, 0.3828329 , 0.44641996, 0.4446403 ,
       0.08676116, 0.24292748, 0.63716174, 0.14630338, 0.49348687,
       0.90616509, 0.81849973, 0.84486983, 0.04786377, 0.5457139 ])

In [103]:
d = a.ravel()
# ravel（）返回的是视图，意味着改变元素的值会影响原始数组；
# flatten（）返回的是拷贝，意味着改变元素的值不会影响原始数组。
d

array([0.66236332, 0.48459376, 0.3828329 , 0.44641996, 0.4446403 ,
       0.08676116, 0.24292748, 0.63716174, 0.14630338, 0.49348687,
       0.90616509, 0.81849973, 0.84486983, 0.04786377, 0.5457139 ])

In [104]:
d = 0
type(d)

int

In [105]:
d[:] = 0
d

TypeError: 'int' object does not support item assignment

In [106]:
a

array([[0.66236332, 0.48459376, 0.3828329 ],
       [0.44641996, 0.4446403 , 0.08676116],
       [0.24292748, 0.63716174, 0.14630338],
       [0.49348687, 0.90616509, 0.81849973],
       [0.84486983, 0.04786377, 0.5457139 ]])

In [107]:
c

array([0.66236332, 0.48459376, 0.3828329 , 0.44641996, 0.4446403 ,
       0.08676116, 0.24292748, 0.63716174, 0.14630338, 0.49348687,
       0.90616509, 0.81849973, 0.84486983, 0.04786377, 0.5457139 ])

In [108]:
np.copy?

建议: 当你不想改变原数组的时候使用np.copy

# 数组操作

## 数学操作

In [109]:
x = np.random.random((3,3))
y = np.random.random((3,3))
print(x, '\n\n', y)

[[0.00478706 0.69398988 0.17051873]
 [0.05690161 0.87268301 0.34534456]
 [0.08603063 0.99353166 0.49449716]] 

 [[0.4967805  0.59221269 0.51444767]
 [0.13595585 0.96563001 0.4532149 ]
 [0.30457906 0.60321057 0.3948684 ]]


In [110]:
x+y, x*y, x/y, x-y

(array([[0.50156756, 1.28620257, 0.6849664 ],
        [0.19285746, 1.83831302, 0.79855946],
        [0.39060968, 1.59674223, 0.88936556]]),
 array([[0.00237812, 0.41098961, 0.08772296],
        [0.00773611, 0.8426889 , 0.1565153 ],
        [0.02620313, 0.5993088 , 0.1952613 ]]),
 array([[0.00963617, 1.17185918, 0.33145982],
        [0.41853008, 0.9037447 , 0.76198853],
        [0.28245746, 1.6470727 , 1.25230876]]),
 array([[-0.49199344,  0.10177719, -0.34392894],
        [-0.07905424, -0.092947  , -0.10787034],
        [-0.21854843,  0.39032109,  0.09962876]]))

In [111]:
np.sin(x), np.sqrt(y)

(array([[0.00478704, 0.63960928, 0.16969358],
        [0.05687091, 0.76605626, 0.33852091],
        [0.08592454, 0.83795855, 0.47458911]]),
 array([[0.70482657, 0.76955357, 0.71725007],
        [0.36872191, 0.98266475, 0.67321238],
        [0.55188682, 0.77666632, 0.62838555]]))

In [112]:
x@y, x.dot(y) # 矩阵乘法， x.dot(y) in py2

(array([[0.14866653, 0.77583111, 0.38432171],
        [0.25209869, 1.08470224, 0.5611515 ],
        [0.32842826, 1.30861833, 0.68980291]]),
 array([[0.14866653, 0.77583111, 0.38432171],
        [0.25209869, 1.08470224, 0.5611515 ],
        [0.32842826, 1.30861833, 0.68980291]]))

In [113]:
x.T, x.T.T # 转置

(array([[0.00478706, 0.05690161, 0.08603063],
        [0.69398988, 0.87268301, 0.99353166],
        [0.17051873, 0.34534456, 0.49449716]]),
 array([[0.00478706, 0.69398988, 0.17051873],
        [0.05690161, 0.87268301, 0.34534456],
        [0.08603063, 0.99353166, 0.49449716]]))

In [114]:
dir(x)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',
 '__pow__',
 '__radd__',
 '__rand__',
 '__rdivmod__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '_

# aggregate function 聚合函数

In [115]:
z = np.arange(6).reshape(2, 3)
z

array([[0, 1, 2],
       [3, 4, 5]])

In [116]:
np.max(z), np.max(z, axis=0), np.max(z, axis=1)

(5, array([3, 4, 5]), array([2, 5]))

In [117]:
z.shape

(2, 3)

In [118]:
np.sum(z), np.sum(z, axis=0), np.sum(z, axis=1)

(15, array([3, 5, 7]), array([ 3, 12]))

In [119]:
a = np.arange(21)
b = a.reshape(3, 7)
b

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20]])

In [120]:
np.sum(b, axis=0)

array([21, 24, 27, 30, 33, 36, 39])

In [121]:
a = np.random.rand(10, 9, 7)

In [123]:
a.sum(axis=2).shape

(10, 9)

## 条件表达式

In [125]:
a = np.random.random(10)*2 + -1 # random with(-1, 1)
a

array([ 0.82549322,  0.88507386,  0.77131664,  0.15380164, -0.51415633,
        0.46988267, -0.22524966, -0.84499389,  0.61726379, -0.29510472])

In [126]:
np.where(a>0.3)

(array([0, 1, 2, 5, 8], dtype=int64),)

In [127]:
np.where((a>0.3) & (np.sin(a)>0.6))

(array([0, 1, 2], dtype=int64),)

In [128]:
a[np.where((a>0.3) & (np.sin(a)>0.6))]

array([0.82549322, 0.88507386, 0.77131664])

In [129]:
np.select([a>0, a<0], [a, a*-1])

array([0.82549322, 0.88507386, 0.77131664, 0.15380164, 0.51415633,
       0.46988267, 0.22524966, 0.84499389, 0.61726379, 0.29510472])

In [132]:
a = np.random.rand(2, 3)
a

array([[0.18626821, 0.46114838, 0.68991464],
       [0.31148588, 0.43054487, 0.47752192]])

In [133]:
np.where(a>0.5)

(array([0], dtype=int64), array([2], dtype=int64))

## Broadcasting(广播)

In [135]:
a = np.tile(np.arange(0, 40, 10), (3, 1)).T
b = np.array([0, 1, 2])
c = np.empty_like(a)

for i in range(a.shape[0]):
    c[i, :] = a[i, :] + b
print(a, "\n\n",c)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [136]:
b1 = np.tile(b, (a.shape[0], 1))
c = a + b1
print(a, "\n\n", a + b)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [137]:
np.tile(b, (a.shape[0], 3))

array([[0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2],
       [0, 1, 2, 0, 1, 2, 0, 1, 2]])

In [138]:
c = a+b
print(a, "\n\n", c)

[[ 0  0  0]
 [10 10 10]
 [20 20 20]
 [30 30 30]] 

 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [139]:
a = np.arange(0, 40, 10)
a = a.reshape(4, 1)
# a = a[:, np.newaxis]  # adds a new axis -> 2D array

b = np.array([0, 1, 2])
c = a+b

print(a, "\n\n", b,"\n\n", c)

[[ 0]
 [10]
 [20]
 [30]] 

 [0 1 2] 

 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


In [140]:
a * b

array([[ 0,  0,  0],
       [ 0, 10, 20],
       [ 0, 20, 40],
       [ 0, 30, 60]])

## 数组形状操作

In [141]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [142]:
print(a.ravel(), "\n\n", a.flatten())

[1 2 3 4 5 6] 

 [1 2 3 4 5 6]


In [143]:
a.reshape(-1)

array([1, 2, 3, 4, 5, 6])

In [144]:
a.reshape(2, -1)

array([[1, 2, 3],
       [4, 5, 6]])

In [145]:
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [146]:
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])

In [147]:
np.concatenate((a,b),axis=0)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [148]:
np.concatenate((a,b.T),axis=1)

array([[1, 2, 5],
       [3, 4, 6]])

In [150]:
a1 = np.arange(4)
b1 = a1 + 2
c1 = a1 + 3

In [151]:
a1,b1,c1

(array([0, 1, 2, 3]), array([2, 3, 4, 5]), array([3, 4, 5, 6]))

In [152]:
np.vstack((a1,b1,c1))

array([[0, 1, 2, 3],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

In [153]:
np.hstack((a1,b1,c1))

array([0, 1, 2, 3, 2, 3, 4, 5, 3, 4, 5, 6])

In [154]:
>>> a = np.array((1,2,3))
>>> b = np.array((2,3,4))
>>> np.hstack((a,b))

array([1, 2, 3, 2, 3, 4])

# 例子
## 康威生命游戏
当前细胞为存活状态时，当周围低于2个（不包含2个）存活细胞时， 该细胞变成死亡状态。（模拟生命数量稀少）

当前细胞为存活状态时，当周围有2个或3个存活细胞时， 该细胞保持原样。

当前细胞为存活状态时，当周围有3个以上的存活细胞时，该细胞变成死亡状态。（模拟生命数量过多）

当前细胞为死亡状态时，当周围有3个存活细胞时，该细胞变成存活状态。 （模拟繁殖）

Ref:

康威生命游戏: 中文, 英文

In [155]:
def compute_neighbours(Z):
    shape = len(Z), len(Z[0])
    N = [[0,]*(shape[0]) for i in range(shape[1])]
    for x in range(1, shape[0]-1):
        for y in range(1, shape[0]-1):
            N[x][y] = Z[x-1][y-1]+Z[x][y-1]+Z[x+1][y-1] \
                    + Z[x-1][y]            +Z[x+1][y]   \
                    + Z[x-1][y+1]+Z[x][y+1]+Z[x+1][y+1]
    return N

# 矩阵乘法

In [156]:
%pylab inline
import numpy as np

Populating the interactive namespace from numpy and matplotlib


In [157]:
import numba
from numba import njit, vectorize

In [159]:
m = 5
n = 3
p = 6
a = np.random.rand(n, m)
b = np.random.rand(m, p)

In [160]:
c0 = a@b
c0

array([[1.88642717, 0.85808911, 1.35602706, 1.20631731, 1.82202168,
        1.77522367],
       [1.36907824, 0.98954491, 1.0826303 , 0.66959323, 1.06166563,
        1.4297614 ],
       [1.16299861, 0.69073366, 0.93635839, 0.68936579, 1.09964801,
        1.25724231]])

In [161]:
t0 = %timeit -o  a@b

The slowest run took 20.52 times longer than the fastest. This could mean that an intermediate result is being cached.
1000000 loops, best of 3: 805 ns per loop


# 分段函数
$$ 
\Theta(x)=\left\{\begin{array}{l}{0, x<0} \\ {\frac{1}{2}, x=0} \\ {1, x>0}\end{array}\right.
 $$